version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies..."
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building and packaging FastAPI app..."
      - zip -r ../app.zip ./*
artifacts:
  files:
    - ../app.zip
