version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20     
    commands:
      - echo "SRC: $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - pwd && ls -la
      - cd frontend
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Next.js app..."
      - npm run build

artifacts:
  files:
    - frontend/.next/**/*     
    - frontend/package.json   
    - frontend/next.config.mjs
  discard-paths: no









# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - echo "Installing Python dependencies..."
#       - python3 -m venv venv
#       - source venv/bin/activate
#       - pip install --upgrade pip
#       - pip install -r requirements.txt
#   build:
#     commands:
#       - echo "Building and packaging FastAPI app..."
#       - zip -r ../app.zip ./*
# artifacts:
#   files:
#     - ../app.zip
